# Generated by Django 6.0.5 on 2026-07-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="members", to="whatsapp.group"),
        ),
    ]
